version: '3.8'

services:
  postgres_mimiciii:
    image: duanegoodner/postgres_mimiciii
    build:
      context: ../
      dockerfile: ./docker/Dockerfile
      args:
        - PRIMARY_USER=duane
        - LOCAL_MIMICIII_BUILD_TOOLS=./mimic-code-fork/mimic-iii/buildmimic
        - POSTGRES_ENTRYPOINT=/docker-entrypoint-initdb.d
    environment:
      - MIMIC_PASSWORD=mimic
      - BUILD_MIMIC=1
      - POSTGRES_PASSWORD=postgres
      - PGDATA=/var/lib/postgresql/data
    container_name: postgres_mimiciii
    volumes:
      - ${LOCAL_CSV_FOR_DB_BUILD}:/mimic_data
      - postgres_mimiciii_data:/var/lib/postgresql/data
    ports:
      - 5555:5432
    init: true
    stdin_open: true
    tty: true

volumes:
  postgres_mimiciii_data:

  # Below code not needed when using Docker named volume
  # Use this service to ensure local user has access to mapped db
  # See https://stackoverflow.com/a/75099809 for details
  # postgres_permissions:
  #   image: duanegoodner/postgres_mimiciii
  #   user: root
  #   volumes:
  #     - ${LOCAL_DB}:/var/lib/postgresql/data
  #   entrypoint:
  #     [
  #       "/bin/bash",
  #       "/docker-entrypoint-initdb.d/postgres_data_permissions/main.sh"
  #     ]
  #   depends_on:
  #     - mimiciii_db