version: '3.8'

services:
  mimiciii_db:
    image: ${IMAGE_NAME}
    restart: always
    build:
      context: ../
      dockerfile: ./docker/Dockerfile
      args:
        - PRIMARY_USER=${USER}
        - LOCAL_MIMICIII_BUILD_TOOLS=${LOCAL_MIMICIII_BUILD_TOOLS}
        - POSTGRES_ENTRYPOINT=${POSTGRES_ENTRYPOINT}
    environment:
      # - MIMIC_USERNAME=${MIMIC_USERNAME}
      - MIMIC_PASSWORD=${MIMIC_PASSWORD}
      - BUILD_MIMIC=${BUILD_MIMIC}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - PGDATA=${PGDATA}
      # - LOCAL_DB_OWNER=${USER}
    container_name: ${CONTAINER_NAME}
    volumes:
      - ${LOCAL_INPUT_CSV}:${CONTAINER_INPUT_CSV}
      - ${LOCAL_SQL_DIR}:${CONTAINER_SQL_DIR}
      - ${LOCAL_OUTPUT_CSV}:${CONTAINER_OUTPUT_CSV}
      - ${LOCAL_DB}:${PGDATA}
    ports:
      - ${PG_HOST_PORT}:5432
    init: true
    stdin_open: true
    tty: true

  # Use this service to ensure local user has access to mapped db
  # See https://stackoverflow.com/a/75099809 for details
  postgres_permissions:
    image: ${IMAGE_NAME}
    user: root
    volumes:
      - ${LOCAL_DB}:${PGDATA}
    entrypoint:
      [
        "/bin/bash",
        "/docker-entrypoint-initdb.d/postgres_data_permissions/main.sh"
      ]
    depends_on:
      - mimiciii_db