version: "3.8"

services:
  postgres_mimiciii:
    image: postgres_mimiciii
    container_name: postgres_mimiciii
    volumes:
      - postgres_mimiciii_data:/var/lib/postgresql/data
    ports:
      - 5555:5432
    init: true
    stdin_open: true
    tty: true

volumes:
  postgres_mimiciii_data: